.PHONY: all, test, testno, no
all:
	gcc -g -std=gnu11 -Wall -Wextra -O2 5.c -o 5

no:
	gcc -g -std=gnu11 -Wall -Wextra 5.c -o 5

test:
	gcc -g -std=gnu11 -Wall -Wextra -O2 test5.c -o test

testno:
	gcc -g -std=gnu11 -Wall -Wextra test5.c -o testno
