2n: 2n.c
	gcc -g -std=gnu11 -Wall -Wextra $< -o $@

prod: prod.c
	gcc -g -std=gnu11 -Wall -Wextra $< -lm -o $@

fm: fm.c
	gcc -std=gnu11 -Wall -Wextra -O2 $< -o $@

fr: fr.c
	gcc -g -std=gnu11 -Wall -Wextra $< -lm -o $@
